# Generated by Django 6.0.4 on 2026-04-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('district_manager', 'District Manager'), ('branch_manager', 'Branch Manager'), ('tattoo_artist', 'Tattoo Artist'), ('body_piercer', 'Body Piercer'), ('staff', 'Staff'), ('clock_in_user', 'Clock In User')], default='staff', max_length=20),
        ),
    ]
