# Generated by Django 6.0.4 on 2026-05-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0010_alter_activitylog_action_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='user_role_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='user_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['location'], name='user_location_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='user_role_active_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['location', 'role'], name='user_location_role_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['location', 'role', 'is_active'], name='user_location_role_active_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_suspended'], name='user_is_suspended_idx'),
        ),
    ]
