# Generated by Django 6.0.4 on 2026-05-21 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0015_remove_task_task_completion_requires_timestamp_and_more'),
        ('users', '0003_user_user_role_idx_user_user_is_active_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_approved', 'Task Approved'), ('task_rejected', 'Task Rejected'), ('task_due_soon', 'Task Due Soon'), ('system', 'System')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_notifications', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_notifications', to='admin_api.task')),
            ],
            options={
                'db_table': 'app_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient'], name='appnotif_recipient_idx'), models.Index(fields=['is_read'], name='appnotif_is_read_idx'), models.Index(fields=['recipient', 'is_read'], name='appnotif_recipient_read_idx'), models.Index(fields=['created_at'], name='appnotif_created_at_idx')],
            },
        ),
    ]
