# Generated by Django 6.0.4 on 2026-07-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_devicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='appnotification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='admin_notifications/'),
        ),
    ]
