# Generated by Django 6.0.4 on 2026-04-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0003_activitylog_actor_activitylog_target_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('awaiting_review', 'Awaiting Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
