# Generated by Django 6.0.4 on 2026-04-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0004_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_fired',
            field=models.BooleanField(default=False),
        ),
    ]
