# Generated by Django 6.0.4 on 2026-04-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0006_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='splashscreen',
            old_name='image_url',
            new_name='app_image_url',
        ),
        migrations.AddField(
            model_name='splashscreen',
            name='web_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
