# Generated by Django 6.0.4 on 2026-04-27 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0007_rename_image_url_splashscreen_app_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrsession',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_sessions', to='admin_api.location'),
        ),
    ]
