# Generated by Django 6.0.4 on 2026-05-02 07:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0009_alter_qrsession_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('task_completed', 'Task Completed'), ('task_assigned', 'Task Assigned'), ('task_approved', 'Task Approved'), ('task_rejected', 'Task Rejected'), ('task_overdue', 'Task Overdue'), ('user_added', 'User Added'), ('user_suspended', 'User Suspended'), ('user_activated', 'User Activated')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['created_at'], name='actlog_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action'], name='actlog_action_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='attendance_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='attendance_status_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['location'], name='attendance_location_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['user', 'date'], name='attendance_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['location', 'date'], name='attendance_location_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status', 'date'], name='attendance_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='instruction',
            index=models.Index(fields=['created_at'], name='instruction_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['status'], name='location_status_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status'], name='notif_status_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notif_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='qrsession',
            index=models.Index(fields=['is_active'], name='qr_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='qrsession',
            index=models.Index(fields=['location', 'is_active'], name='qr_location_active_idx'),
        ),
        migrations.AddIndex(
            model_name='qrsession',
            index=models.Index(fields=['token'], name='qr_token_idx'),
        ),
        migrations.AddIndex(
            model_name='qrsession',
            index=models.Index(fields=['expires_at'], name='qr_expires_at_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='task_status_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['location'], name='task_location_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to'], name='task_assigned_to_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_at'], name='task_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='task_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['location', 'status'], name='task_location_status_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'created_at'], name='task_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status'], name='task_assigned_status_idx'),
        ),
        migrations.AddIndex(
            model_name='userworkschedule',
            index=models.Index(fields=['user'], name='schedule_user_idx'),
        ),
        migrations.AddIndex(
            model_name='userworkschedule',
            index=models.Index(fields=['user', 'day'], name='schedule_user_day_idx'),
        ),
    ]
