# Generated by Django 6.0.4 on 2026-05-02 11:00

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0011_activitylog_actlog_actor_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='instruction',
            index=django.contrib.postgres.indexes.GinIndex(fields=['role_visibility'], name='instruct_role_vis_gin'),
        ),
    ]
