# Generated by Django 6.0.4 on 2026-05-02 17:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0012_instruction_instruct_role_vis_gin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userworkschedule',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_date_attendance'),
        ),
        migrations.AddConstraint(
            model_name='userworkschedule',
            constraint=models.UniqueConstraint(fields=('user', 'day'), name='unique_user_day_schedule'),
        ),
    ]
