# Generated by Django 6.0.4 on 2026-05-02 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0013_alter_attendance_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'absent'), ('clock_in__isnull', False), _connector='OR'), name='attendance_present_requires_clockin'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'rejected', 'overdue']), ('completed_at__isnull', False), _connector='OR'), name='task_completion_requires_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'rejected'), _negated=True), ('rejection_reason__isnull', False), _connector='OR'), name='task_rejection_requires_reason'),
        ),
        migrations.AddConstraint(
            model_name='userworkschedule',
            constraint=models.CheckConstraint(condition=models.Q(('is_active', False), models.Q(('start_time__isnull', False), ('end_time__isnull', False)), _connector='OR'), name='schedule_active_requires_time'),
        ),
    ]
