# Generated by Django 6.0.4 on 2026-05-02 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0014_attendance_attendance_present_requires_clockin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='task_completion_requires_timestamp',
        ),
        migrations.AlterField(
            model_name='notification',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(condition=models.Q(('clock_out__isnull', True), ('clock_out__gt', models.F('clock_in')), _connector='OR'), name='attendance_clock_out_after_clock_in'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(('recipient__isnull', False), models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), _connector='OR'), name='notification_requires_target'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'rejected', 'overdue']), models.Q(('completed_at__isnull', False), ('completed_by__isnull', False)), _connector='OR'), name='task_completion_requires_data'),
        ),
        migrations.AddConstraint(
            model_name='userworkschedule',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__isnull', True), ('end_time__isnull', True), ('end_time__gt', models.F('start_time')), _connector='OR'), name='schedule_end_after_start'),
        ),
    ]
