# Generated by Django 6.0.4 on 2026-06-15 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0017_task_assigned_to_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='admin_notifications/')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_created_at_idx',
        ),
        migrations.RemoveConstraint(
            model_name='notification',
            name='notification_requires_target',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_assigned_to_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_assigned_status_idx',
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_admin_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_admin_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='location',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sent_by',
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['recipient', 'is_read'], name='admin_notif_recipient_read_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['created_at'], name='admin_notif_created_at_idx'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
