# Generated by Django 6.0.4 on 2026-06-16 04:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0018_admin_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='adminnotification',
            name='admin_notif_recipient_read_idx',
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='recipients',
            field=models.ManyToManyField(related_name='received_admin_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='adminnotification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='adminnotification',
            name='recipient',
        ),
    ]
